version = 0.1
[default.deploy.parameters]
stack_name = "amazon-bedrock-images-titan"
resolve_s3 = true
s3_prefix = "amazon-bedrock-images-titan"
region = "us-east-1"
profile = "damiensandbox"
capabilities = "CAPABILITY_IAM"
image_repositories = []
